[package]
name = "meeple_bots_catalog"
version = "0.1.0"
edition = "2024"

[dependencies]
meeple_bots_mcts_agent = { path = "../../agents/mcts" }
meeple_bots_random_agent = { path = "../../agents/random" }
meeple_bots_simulation = { path = "../simulation" }
meeple_bots_tic_tac_toe = { path = "../../games/tic-tac-toe" }
