[workspace]
resolver = "3"
members = [
    "crates/core",
    "crates/evaluation",
    "crates/simulation",
    "crates/catalog",
    "crates/python-bindings",
    "games/boop",
    "games/splendor",
    "games/cant-stop",
    "games/lost-cities",
    "games/connect-four",
    "games/connect6",
    "games/spirits-of-the-forest",
    "games/tic-tac-toe",
    "agents/random",
    "agents/mcts",
]
