[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "meeple-bots"
version = "0.1.0"
description = "Framework modular para simular juegos de mesa con agentes inteligentes"
readme = "README.md"
requires-python = ">=3.11"

[tool.setuptools]
package-dir = {"" = "python/src"}

[tool.setuptools.packages.find]
where = ["python/src"]
