//! Base-game mechanical data; IDs follow the verified CSV row order.
use super::{Card, Noble};
pub const CARDS: [Card; 90] = [
    Card {
        id: 0,
        tier: 1,
        bonus: 4,
        points: 0,
        cost: [1, 1, 1, 1, 0],
    },
    Card {
        id: 1,
        tier: 1,
        bonus: 4,
        points: 0,
        cost: [1, 2, 1, 1, 0],
    },
    Card {
        id: 2,
        tier: 1,
        bonus: 4,
        points: 0,
        cost: [2, 2, 0, 1, 0],
    },
    Card {
        id: 3,
        tier: 1,
        bonus: 4,
        points: 0,
        cost: [0, 0, 1, 3, 1],
    },
    Card {
        id: 4,
        tier: 1,
        bonus: 4,
        points: 0,
        cost: [0, 0, 2, 1, 0],
    },
    Card {
        id: 5,
        tier: 1,
        bonus: 4,
        points: 0,
        cost: [2, 0, 2, 0, 0],
    },
    Card {
        id: 6,
        tier: 1,
        bonus: 4,
        points: 0,
        cost: [0, 0, 3, 0, 0],
    },
    Card {
        id: 7,
        tier: 1,
        bonus: 4,
        points: 1,
        cost: [0, 4, 0, 0, 0],
    },
    Card {
        id: 8,
        tier: 1,
        bonus: 1,
        points: 0,
        cost: [1, 0, 1, 1, 1],
    },
    Card {
        id: 9,
        tier: 1,
        bonus: 1,
        points: 0,
        cost: [1, 0, 1, 2, 1],
    },
    Card {
        id: 10,
        tier: 1,
        bonus: 1,
        points: 0,
        cost: [1, 0, 2, 2, 0],
    },
    Card {
        id: 11,
        tier: 1,
        bonus: 1,
        points: 0,
        cost: [0, 1, 3, 1, 0],
    },
    Card {
        id: 12,
        tier: 1,
        bonus: 1,
        points: 0,
        cost: [1, 0, 0, 0, 2],
    },
    Card {
        id: 13,
        tier: 1,
        bonus: 1,
        points: 0,
        cost: [0, 0, 2, 0, 2],
    },
    Card {
        id: 14,
        tier: 1,
        bonus: 1,
        points: 0,
        cost: [0, 0, 0, 0, 3],
    },
    Card {
        id: 15,
        tier: 1,
        bonus: 1,
        points: 1,
        cost: [0, 0, 0, 4, 0],
    },
    Card {
        id: 16,
        tier: 1,
        bonus: 0,
        points: 0,
        cost: [0, 1, 1, 1, 1],
    },
    Card {
        id: 17,
        tier: 1,
        bonus: 0,
        points: 0,
        cost: [0, 1, 2, 1, 1],
    },
    Card {
        id: 18,
        tier: 1,
        bonus: 0,
        points: 0,
        cost: [0, 2, 2, 0, 1],
    },
    Card {
        id: 19,
        tier: 1,
        bonus: 0,
        points: 0,
        cost: [3, 1, 0, 0, 1],
    },
    Card {
        id: 20,
        tier: 1,
        bonus: 0,
        points: 0,
        cost: [0, 0, 0, 2, 1],
    },
    Card {
        id: 21,
        tier: 1,
        bonus: 0,
        points: 0,
        cost: [0, 2, 0, 0, 2],
    },
    Card {
        id: 22,
        tier: 1,
        bonus: 0,
        points: 0,
        cost: [0, 3, 0, 0, 0],
    },
    Card {
        id: 23,
        tier: 1,
        bonus: 0,
        points: 1,
        cost: [0, 0, 4, 0, 0],
    },
    Card {
        id: 24,
        tier: 1,
        bonus: 2,
        points: 0,
        cost: [1, 1, 0, 1, 1],
    },
    Card {
        id: 25,
        tier: 1,
        bonus: 2,
        points: 0,
        cost: [1, 1, 0, 1, 2],
    },
    Card {
        id: 26,
        tier: 1,
        bonus: 2,
        points: 0,
        cost: [0, 1, 0, 2, 2],
    },
    Card {
        id: 27,
        tier: 1,
        bonus: 2,
        points: 0,
        cost: [1, 3, 1, 0, 0],
    },
    Card {
        id: 28,
        tier: 1,
        bonus: 2,
        points: 0,
        cost: [2, 1, 0, 0, 0],
    },
    Card {
        id: 29,
        tier: 1,
        bonus: 2,
        points: 0,
        cost: [0, 2, 0, 2, 0],
    },
    Card {
        id: 30,
        tier: 1,
        bonus: 2,
        points: 0,
        cost: [0, 0, 0, 3, 0],
    },
    Card {
        id: 31,
        tier: 1,
        bonus: 2,
        points: 1,
        cost: [0, 0, 0, 0, 4],
    },
    Card {
        id: 32,
        tier: 1,
        bonus: 3,
        points: 0,
        cost: [1, 1, 1, 0, 1],
    },
    Card {
        id: 33,
        tier: 1,
        bonus: 3,
        points: 0,
        cost: [2, 1, 1, 0, 1],
    },
    Card {
        id: 34,
        tier: 1,
        bonus: 3,
        points: 0,
        cost: [2, 0, 1, 0, 2],
    },
    Card {
        id: 35,
        tier: 1,
        bonus: 3,
        points: 0,
        cost: [1, 0, 0, 1, 3],
    },
    Card {
        id: 36,
        tier: 1,
        bonus: 3,
        points: 0,
        cost: [0, 2, 1, 0, 0],
    },
    Card {
        id: 37,
        tier: 1,
        bonus: 3,
        points: 0,
        cost: [2, 0, 0, 2, 0],
    },
    Card {
        id: 38,
        tier: 1,
        bonus: 3,
        points: 0,
        cost: [3, 0, 0, 0, 0],
    },
    Card {
        id: 39,
        tier: 1,
        bonus: 3,
        points: 1,
        cost: [4, 0, 0, 0, 0],
    },
    Card {
        id: 40,
        tier: 2,
        bonus: 4,
        points: 1,
        cost: [3, 2, 2, 0, 0],
    },
    Card {
        id: 41,
        tier: 2,
        bonus: 4,
        points: 1,
        cost: [3, 0, 3, 0, 2],
    },
    Card {
        id: 42,
        tier: 2,
        bonus: 4,
        points: 2,
        cost: [0, 1, 4, 2, 0],
    },
    Card {
        id: 43,
        tier: 2,
        bonus: 4,
        points: 2,
        cost: [0, 0, 5, 3, 0],
    },
    Card {
        id: 44,
        tier: 2,
        bonus: 4,
        points: 2,
        cost: [5, 0, 0, 0, 0],
    },
    Card {
        id: 45,
        tier: 2,
        bonus: 4,
        points: 3,
        cost: [0, 0, 0, 0, 6],
    },
    Card {
        id: 46,
        tier: 2,
        bonus: 1,
        points: 1,
        cost: [0, 2, 2, 3, 0],
    },
    Card {
        id: 47,
        tier: 2,
        bonus: 1,
        points: 1,
        cost: [0, 2, 3, 0, 3],
    },
    Card {
        id: 48,
        tier: 2,
        bonus: 1,
        points: 2,
        cost: [5, 3, 0, 0, 0],
    },
    Card {
        id: 49,
        tier: 2,
        bonus: 1,
        points: 2,
        cost: [2, 0, 0, 1, 4],
    },
    Card {
        id: 50,
        tier: 2,
        bonus: 1,
        points: 2,
        cost: [0, 5, 0, 0, 0],
    },
    Card {
        id: 51,
        tier: 2,
        bonus: 1,
        points: 3,
        cost: [0, 6, 0, 0, 0],
    },
    Card {
        id: 52,
        tier: 2,
        bonus: 0,
        points: 1,
        cost: [0, 0, 3, 2, 2],
    },
    Card {
        id: 53,
        tier: 2,
        bonus: 0,
        points: 1,
        cost: [2, 3, 0, 3, 0],
    },
    Card {
        id: 54,
        tier: 2,
        bonus: 0,
        points: 2,
        cost: [0, 0, 1, 4, 2],
    },
    Card {
        id: 55,
        tier: 2,
        bonus: 0,
        points: 2,
        cost: [0, 0, 0, 5, 3],
    },
    Card {
        id: 56,
        tier: 2,
        bonus: 0,
        points: 2,
        cost: [0, 0, 0, 5, 0],
    },
    Card {
        id: 57,
        tier: 2,
        bonus: 0,
        points: 3,
        cost: [6, 0, 0, 0, 0],
    },
    Card {
        id: 58,
        tier: 2,
        bonus: 2,
        points: 1,
        cost: [3, 0, 2, 3, 0],
    },
    Card {
        id: 59,
        tier: 2,
        bonus: 2,
        points: 1,
        cost: [2, 3, 0, 0, 2],
    },
    Card {
        id: 60,
        tier: 2,
        bonus: 2,
        points: 2,
        cost: [4, 2, 0, 0, 1],
    },
    Card {
        id: 61,
        tier: 2,
        bonus: 2,
        points: 2,
        cost: [0, 5, 3, 0, 0],
    },
    Card {
        id: 62,
        tier: 2,
        bonus: 2,
        points: 2,
        cost: [0, 0, 5, 0, 0],
    },
    Card {
        id: 63,
        tier: 2,
        bonus: 2,
        points: 3,
        cost: [0, 0, 6, 0, 0],
    },
    Card {
        id: 64,
        tier: 2,
        bonus: 3,
        points: 1,
        cost: [2, 0, 0, 2, 3],
    },
    Card {
        id: 65,
        tier: 2,
        bonus: 3,
        points: 1,
        cost: [0, 3, 0, 2, 3],
    },
    Card {
        id: 66,
        tier: 2,
        bonus: 3,
        points: 2,
        cost: [1, 4, 2, 0, 0],
    },
    Card {
        id: 67,
        tier: 2,
        bonus: 3,
        points: 2,
        cost: [3, 0, 0, 0, 5],
    },
    Card {
        id: 68,
        tier: 2,
        bonus: 3,
        points: 2,
        cost: [0, 0, 0, 0, 5],
    },
    Card {
        id: 69,
        tier: 2,
        bonus: 3,
        points: 3,
        cost: [0, 0, 0, 6, 0],
    },
    Card {
        id: 70,
        tier: 3,
        bonus: 4,
        points: 3,
        cost: [3, 3, 5, 3, 0],
    },
    Card {
        id: 71,
        tier: 3,
        bonus: 4,
        points: 4,
        cost: [0, 0, 0, 7, 0],
    },
    Card {
        id: 72,
        tier: 3,
        bonus: 4,
        points: 4,
        cost: [0, 0, 3, 6, 3],
    },
    Card {
        id: 73,
        tier: 3,
        bonus: 4,
        points: 5,
        cost: [0, 0, 0, 7, 3],
    },
    Card {
        id: 74,
        tier: 3,
        bonus: 1,
        points: 3,
        cost: [3, 0, 3, 3, 5],
    },
    Card {
        id: 75,
        tier: 3,
        bonus: 1,
        points: 4,
        cost: [7, 0, 0, 0, 0],
    },
    Card {
        id: 76,
        tier: 3,
        bonus: 1,
        points: 4,
        cost: [6, 3, 0, 0, 3],
    },
    Card {
        id: 77,
        tier: 3,
        bonus: 1,
        points: 5,
        cost: [7, 3, 0, 0, 0],
    },
    Card {
        id: 78,
        tier: 3,
        bonus: 0,
        points: 3,
        cost: [0, 3, 3, 5, 3],
    },
    Card {
        id: 79,
        tier: 3,
        bonus: 0,
        points: 4,
        cost: [0, 0, 0, 0, 7],
    },
    Card {
        id: 80,
        tier: 3,
        bonus: 0,
        points: 4,
        cost: [3, 0, 0, 3, 6],
    },
    Card {
        id: 81,
        tier: 3,
        bonus: 0,
        points: 5,
        cost: [3, 0, 0, 0, 7],
    },
    Card {
        id: 82,
        tier: 3,
        bonus: 2,
        points: 3,
        cost: [5, 3, 0, 3, 3],
    },
    Card {
        id: 83,
        tier: 3,
        bonus: 2,
        points: 4,
        cost: [0, 7, 0, 0, 0],
    },
    Card {
        id: 84,
        tier: 3,
        bonus: 2,
        points: 4,
        cost: [3, 6, 3, 0, 0],
    },
    Card {
        id: 85,
        tier: 3,
        bonus: 2,
        points: 5,
        cost: [0, 7, 3, 0, 0],
    },
    Card {
        id: 86,
        tier: 3,
        bonus: 3,
        points: 3,
        cost: [3, 5, 3, 0, 3],
    },
    Card {
        id: 87,
        tier: 3,
        bonus: 3,
        points: 4,
        cost: [0, 0, 7, 0, 0],
    },
    Card {
        id: 88,
        tier: 3,
        bonus: 3,
        points: 4,
        cost: [0, 3, 6, 3, 0],
    },
    Card {
        id: 89,
        tier: 3,
        bonus: 3,
        points: 5,
        cost: [0, 0, 7, 3, 0],
    },
];
pub const NOBLES: [Noble; 10] = [
    Noble {
        id: 0,
        requirements: [0, 0, 4, 4, 0],
        points: 3,
    },
    Noble {
        id: 1,
        requirements: [0, 4, 4, 0, 0],
        points: 3,
    },
    Noble {
        id: 2,
        requirements: [4, 4, 0, 0, 0],
        points: 3,
    },
    Noble {
        id: 3,
        requirements: [4, 0, 0, 0, 4],
        points: 3,
    },
    Noble {
        id: 4,
        requirements: [0, 0, 0, 4, 4],
        points: 3,
    },
    Noble {
        id: 5,
        requirements: [0, 3, 3, 3, 0],
        points: 3,
    },
    Noble {
        id: 6,
        requirements: [3, 3, 3, 0, 0],
        points: 3,
    },
    Noble {
        id: 7,
        requirements: [3, 3, 0, 0, 3],
        points: 3,
    },
    Noble {
        id: 8,
        requirements: [3, 0, 0, 3, 3],
        points: 3,
    },
    Noble {
        id: 9,
        requirements: [0, 0, 3, 3, 3],
        points: 3,
    },
];
