[package]
name = "meeple_bots_python_bindings"
version = "0.1.0"
edition = "2024"

[lib]
name = "_native"
crate-type = ["cdylib", "rlib"]

[dependencies]
meeple_bots_so_ismcts = { path = "../../agents/so-ismcts" }
meeple_bots_lost_cities = { path = "../../games/lost-cities" }
meeple_bots_connect6 = { path = "../../games/connect6" }
meeple_bots_splendor = { path = "../../games/splendor" }
meeple_bots_cant_stop = { path = "../../games/cant-stop" }
meeple_bots_boop = { path = "../../games/boop" }
meeple_bots_catalog = { path = "../catalog" }
meeple_bots_connect_four = { path = "../../games/connect-four" }
meeple_bots_core = { path = "../core" }
meeple_bots_mcts_agent = { path = "../../agents/mcts" }
meeple_bots_simulation = { path = "../simulation" }
meeple_bots_spirits_of_the_forest = { path = "../../games/spirits-of-the-forest" }
meeple_bots_tic_tac_toe = { path = "../../games/tic-tac-toe" }
pyo3 = "0.29.0"
